# Generated by Django 4.1.2 on 2022-12-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaAutos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='autos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaAutos.auto')),
            ],
        ),
    ]
