# Generated by Django 4.1.2 on 2022-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaAutos', '0002_remove_auto_imagen_imagenauto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos'),
        ),
        migrations.DeleteModel(
            name='ImagenAuto',
        ),
    ]
