# Generated by Django 4.1 on 2022-12-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaAutos', '0006_mensaje_tiempo_mensaje_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_add_imagen_auto', 'Agregar una imagen de auto'), ('can_change_imagen_auto', 'Cambiar una imagen de auto'), ('can_delete_imagen_auto', 'Borrar una imagen de auto')),
            },
        ),
    ]
